"use client";
import { isMobile } from "react-device-detect";
import { Providers } from "../../lib/providers";
import MobileFooter from "./components/Mobile/footer/footer";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "./components/desktop/footer/footer";
import { LazyMotion, domAnimation } from "framer-motion";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Xcaret Front end",
  description: "Generated by create next app!!!",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body
        className={inter.className}
        style={{ display: "flex", flexDirection: "column", height: "100%" }}
      >
        <Providers>
          <LazyMotion features={domAnimation}>
            <div
              style={{ flex: "1 0 auto" }}
              className="max-w-7xl w-full mx-auto" id="content"
            >
              {children}
            </div>
            {isMobile && <MobileFooter />}
            {!isMobile && <Footer />}
          </LazyMotion>
        </Providers>
      </body>
    </html>
  );
}
