import Footer from "./components/(Mobile)/footer/footer";
import Navbar from "./components/(Mobile)/navbar/navbar";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className} style={{display: "flex", flexDirection: "column", height: "100%"}}>
        <div style={{ flex: "1 0 auto" }}>
          <Navbar />
          {children}
        </div>
        <footer className="shrink-0">
          <Footer
            socials={[
              {
                srcUrl: "https://placekitten.com/24/24",
                logo: {
                  srcUrl: "https://placekitten.com/24/24",
                  alt: "dsa",
                },
              },
              {
                srcUrl: "https://placekitten.com/24/24",
                logo: {
                  srcUrl: "https://placekitten.com/24/24",
                  alt: "dsa",
                },
              },
            ]}
            copy={"©Copyright Experiencias Xcaret Hotel S.A.P.I. de C.V."}
            links={[
              {
                srcUrl: "#",
                title: "Términos de Uso Aviso de Privacidad ",
              },
            ]}
          />
        </footer>
      </body>
    </html>
  );
}
